# Use an OpenJDK image
FROM openjdk:17-jdk-alpine

# Set working directory
WORKDIR /app

# Add the JAR file
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar

# Run the application
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
